version: '3.8'

services:
  app:
    build: .
    container_name: github-action-fs-2
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - PORT=8001
    restart: unless-stopped