name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Test
        run: pnpm test

      - name: Run typecheck
        run: pnpm typecheck

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Meta Information
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: wolfiee42/github-action-fs-2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 1024
          script: |
            # Clone/update repository to get docker-compose.yml
            if [ -d "github-action-fs-2" ]; then
              cd github-action-fs-2
              git pull origin main
            else
              git clone https://github.com/wolfiee42/github-action-fs-2.git
              cd github-action-fs-2
            fi
            
            # Pull the latest image
            docker pull wolfiee42/github-action-fs-2:main
            
            # Stop existing services
            docker-compose down || true
            
            # Override for production: use the built image instead of building
            DOCKER_IMAGE=wolfiee42/github-action-fs-2:main NODE_ENV=production CONTAINER_NAME=express-api-starter-prod docker-compose -f docker-compose.yml up -d
            
            # Clean up unused images
            docker image prune -f
